config/routes.rb
Rails.application.routes.draw do
  resources :characters

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  root 'pages#home'

end

app/models/character.rb
class Character < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @character.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h4>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/characters/edit.html.erb
<div class="page-header">
  <%= link_to characters_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @character, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing character</h1>
</div>

<%= render 'form' %>

app/views/characters/index.html.erb
<div class="page-header">
  <%= link_to new_character_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Character
  <% end %>
  <h1>Listing characters</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @characters) do |character| %>
            <td><%= character.name %></td>
            <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/characters/new.html.erb
<div class="page-header">
  <%= link_to characters_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New character</h1>
</div>

<%= render 'form' %>

app/views/characters/show.html.erb
<div class="page-header">
  <%= link_to characters_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_character_path(@character), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show character</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @character.name %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>PathFolio</title>
  <%= favicon_link_tag %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "PathFolio", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(pages_home_path) || current_page?(root_path) %>"><%= link_to "Home", pages_home_path %></li>
          <li class="<%= 'active' if current_page?(pages_about_path) %>"><%= link_to "About", pages_about_path %></li>
          <li class="<%= 'active' if current_page?(pages_contact_path) %>"><%= link_to "Contact", pages_contact_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == "error" ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div class="page-header">
  <h1>About this Project</h1>
</div>
<p>This application will keep track of your characters. Some time in the future. ',=)</p>
<p>For now, it is just a web page. Expect more soon.</p>
<a href="https://github.com/RyanSpittler/PathFolio">Check out the code for this project on GitHub.</a>

app/views/pages/contact.html.erb
<div class="page-header">
  <h1>Contact</h1>
</div>
<p>This project is currently being developed by Ryan Spittler.</p>
<div class="row">
  <div class="col-md-3 col-sm-4 col-xs-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="text-center panel-title">Ryan Spittler</h3>
      </div>
      <div class="text-center">
        <br/>
        <%= image_tag 'Ryan Spittler.jpg', class: 'img-rounded text-center' %>
      </div>
      <h4 class="text-center">
        ryanspittler@gmail.com
      </h4>
      <div class="panel-footer">
        <a class="btn btn-sm btn-block btn-social btn-linkedin" href="https://www.linkedin.com/pub/ryan-spittler/b2/549/480">
          <i class="fa fa-linkedin"></i> Find me on LinkedIn
        </a>
        <a class="btn btn-sm btn-block btn-social btn-github" href="https://github.com/RyanSpittler">
          <i class="fa fa-github"></i> Find me on GitHub
        </a>
        <a class="btn btn-sm btn-block btn-social btn-primary" href="https://ryanspittler.wordpress.com/">
          <%= image_tag 'wordpress_icon.png' %> Read My Blog
        </a>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="page-header">
  <h1>Homepage</h1>
</div>
<p>We'll determine what goes here later. For now, find me in app/views/pages/home.html.erb</p>